language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=fc64d003bdf120b91db2a980408cf2073efe351171845840b1fa6a0d87b658ea
node_js:
  - "9"
cache: yarn
before_install: yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - yarn
  - yarn build
  - yarn test
after_script:
  - cd packages/shared/coverage
  - ../../../cc-test-reporter format-coverage -t clover -o tmp/codeclimate.shared.json clover.xml
  - cd ../../backend/coverage
  - ../../../cc-test-reporter format-coverage -t clover -o tmp/codeclimate.backend.json clover.xml
  - cd ../../../
  - ./cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
  - ./cc-test-reporter upload-coverage -i tmp/codeclimate.total.json
  - greenkeeper-lockfile-upload
