language: node_js
env:
  global:
  - CC_TEST_REPORTER_ID=fc64d003bdf120b91db2a980408cf2073efe351171845840b1fa6a0d87b658ea
node_js:
- '10'
cache:
  yarn: true
  directories:
  - "$HOME/.mongodb-binaries"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
script:
- yarn build
- cd packages/shared
- yarn test
- cd ../backend
- yarn test
after_script:
- cd packages/shared
- "../../cc-test-reporter format-coverage -o /tmp/codeclimate.shared.json"
- cd ../backend
- "../../cc-test-reporter format-coverage -o /tmp/codeclimate.backend.json"
- cd ../../
- "./cc-test-reporter sum-coverage /tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json"
- "./cc-test-reporter upload-coverage -i tmp/codeclimate.total.json"
- greenkeeper-lockfile-upload
deploy:
  provider: s3
  access_key_id: AKIAJOEIOUPV55S53P3Q
  secret_access_key:
    secure: UYWnApToHbsMzElhAHY6QDcpH4ya/UZmXMBzkPw/dt/aT7EuBOmk/OFO7ZbyDuLs1sDnTInYDR8JPTVfjba9Lo5vMBqCUhfJDHLSuoohXioQBDFKZAENjv8c0Gp2enzWjKfYsFEIq27tnJoEfGuVSTgjcPwrp1+bo2VVUOjt0mf9lsBnAXBTq3lPE2S80eoHg9QyFLMzQsxPHdg7YAOcpAXTiZlY60x51qdI7lAp70tFtuL+IRXdP0lUre8HcZOle8s0x/SzD0B26FIv2/SGV3ZSkoHQn4/x4dhOR9Voc6kcWzHEbKmugTnlJkHi/Jpp4nbb0UqephIqR7LLG4BObUzTVXals1b/D6HS8q8CK8ZlcvHym1VRQNAqqErDwpImWZy3NSeVJmvhqtAsUYsg+/OvZBSOM7aGQb+aId+XW8ITj/yqxP3et0J6jcbVNt9eQA6q0moECVOFVC2ft50SGhJyYqoQ5d3eZHKguKRcxtieWMno37NvET+S0fUbmnkJbcaWt+njx04lsACIKBEbu+jl3pRYUC4QfmFYpCwj759AJEuHI2VXbX+NNW4exSUQJg4eIA+kzWBwccUHDTPQFy8uF+v37iG9ZgkGFzyfmx6sjh1VsklYTLA6XbaR8NNXSykBkW+NakdU0b7QLFnTBGHgYH1EGluLkQOtVgkxsCo=
  bucket: timeseries-explorer-frontendbucket-1jueporougkwu
  region: eu-west-1
  on:
    all_branches: true
