language: node_js
node_js:
  - "9"
cache: yarn
script:
  - yarn
  - yarn build
  - yarn test
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload