version: "3"

services:
  backend:
    build: ./packages/backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    links:
      - mongodb
    
  frontend:
    build: ./packages/frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    links:
      - backend
      
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null --bind_ip_all
