Description: Timeseries Explorer

Parameters: 
  DatabaseUser: 
    Type: String
  DatabasePW: 
    Type: String
  MlabUrl:
    Type: String
  BackendDomain:
    Type: String
  FrontendDomain:
    Type: String
  EuWestCertArn:
    Type: String
    AllowedPattern: "arn:aws:acm:.*"
  GlobalCertArn:
    Type: String
    AllowedPattern: "arn:aws:acm:.*"

Resources:
  # Backend
  CodeArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: Enabled

  ProdServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
  ProdInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ProdServiceRole

  EBApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: Backend

  EBBackendTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref EBApplication
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t2.micro
        - Namespace: aws:elb:listener:443
          OptionName: ListenerProtocol
          Value: HTTPS
        - Namespace: aws:elb:listener:443
          OptionName: InstancePort
          Value: 80
        - Namespace: aws:elb:listener:443
          OptionName: InstanceProtocol
          Value: HTTP
        - Namespace: aws:elb:listener:443
          OptionName: SSLCertificateId
          Value: !Ref EuWestCertArn
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_USER
          Value: !Ref DatabaseUser
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_PW
          Value: !Ref DatabasePW
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_MLAB_URL
          Value: !Ref MlabUrl
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: BACKEND_DOMAIN
          Value: !Ref BackendDomain
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: FRONTEND_DOMAIN
          Value: !Ref FrontendDomain
      SolutionStackName: 64bit Amazon Linux 2018.03 v2.11.0 running Docker 18.03.1-ce

  EBEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref EBApplication
      TemplateName: !Ref EBBackendTemplate
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref ProdInstanceProfile
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: !Ref ProdServiceRole
      Tier:
        Name: WebServer
        Type: Standard

  # Frontend
  CloudFrontDist:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref FrontendDomain
        Origins:
        - Id: frontend
          DomainName:
            Fn::GetAtt: [ FrontendBucket , 'DomainName' ]
          S3OriginConfig:
            OriginAccessIdentity:
              Ref: AWS::NoValue
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          Compress: true
          TargetOriginId: frontend
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy : allow-all
        PriceClass: PriceClass_100
        CustomErrorResponses:
        - ErrorCode: 404
          ResponsePagePath: /index.html
          ResponseCode: 200
        ViewerCertificate:
          AcmCertificateArn: !Ref GlobalCertArn
          SslSupportMethod: sni-only
            
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref FrontendBucket
                - /*
      Bucket: !Ref FrontendBucket
      